version: '3' 
services: 
  node: 
    build: . 
    ports: 
      - "8000:8000" 
    expose:
      - "8000" 
    links: 
      - mysql 
    depends_on: 
      - mysql 
  mysql: 
    image: "mysql" 
    ports: 
      - "3306:3306" 
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    expose: 
      - "3306"
